---
- name: Install GIT
  become: true
  apt:
    name:
      - git
    state: present
    update_cache: yes
- name: Install graphics programm
  become: true
  apt:
    name:
      - gimp
      - inkscape
    state: present
    update_cache: yes
- name: Install messangers
  become: true
  apt:
    name:
      - telegram-desktop
    state: present
    update_cache: yes
- name: Install development tools
  become: true
  apt:
    name:
      - nodejs
      - net-tools
      - htop
    state: present
    update_cache: yes
- name: KeePassXC
  become: true
  apt:
    name:
      - keepassxc
    state: present
    update_cache: yes
