---
- name: Install dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Verify fingerprint
  become: true
  apt_key:
    id: 0EBFCD88
    state: present

- name: Set up the repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu/focal stretch stable
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot

- name: Install Docker Compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: 'u+x,g+x'

- name: Set periodic Docker prune
  become: true
  cron:
    name: docker-prune
    job: 'docker system prune -af --filter "until=$((3*30*24))h"'
    minute: '0'
    hour: '1'

- name: Remove useless packages
  become: true
  apt:
    autoclean: yes

- name: Remove useless dependencies
  become: true
  apt:
    autoremove: yes